biblioteca/urls.py
from django.urls import path
from biblioteca import views


app_name = 'biblioteca'


urlpatterns = [
    path('', views.LivroList.as_view(), name='list'),
    path('create/', views.LivroCreate.as_view(), name='create'),
    path('update/<int:pk>', views.LivroUpdate.as_view(), name='update'),
    path('detail/<int:pk>', views.LivroDetail.as_view(), name='detail'),
    path('delete/<int:pk>', views.LivroDelete.as_view(), name='delete'),
]

livraria/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('livros/', include('biblioteca.urls'))
]

biblioteca/models.py
from django.db import models

class Livro(models.Model):
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=200)
    publisher = models.CharField(max_length=200)
    genre = models.CharField(max_length=100)
    year = models.IntegerField(max_length=4)
    description = models.TextField(max_length=500)

    def __str__(self):
        return self.title

biblioteca/forms.py
from django import forms
from biblioteca.models import Livro

class LivroForm(forms.ModelForm):
    class Meta:
        model = Livro
        fields = '__all__'

biblioteca/views.py
from django.db.models import query
from django.shortcuts import render
from django.urls.base import reverse_lazy
from django.views.generic import ListView, CreateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView, UpdateView
from livraria import biblioteca

from livraria.biblioteca.models import Livro

class LivroList(ListView):
    model = Livro
    queryset = Livro.objects.all()
    
class LivroCreate(CreateView):
    model = Livro
    fields = '__all__'
    success_url = reverse_lazy('biblioteca:list')

class LivroUpdate(UpdateView):
    model = Livro
    fields = '__all__'
    success_url = reverse_lazy('biblioteca:list')

class LivroDetail(DetailView):
    queryset = Livro.objects.all()

class LivroDelete(DeleteView):
    queryset = Livro.objects.all()
    success_url = reverse_lazy('biblioteca:list')

templates/biblioteca/livro_confirm_delete.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Excluir Livro</title>
</head>
<body>
Tem certeza de que deseja apagar o cliente '{{ object.title }}' ?
<form action="." method="post">
    {% csrf_token %}
    <input type="submit" value="Sim, desejo excluir">
    <input type="reset" onclick="location.href= '{% url biblioteca:list %}'" value="Não quero apagar mais">

</form>
</body>
</html>

templates/biblioteca/livro_detail.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Visualizar Livro</title>
</head>
<body>

<input type="submit" onclick="location.href = '{% url biblioteca:list %}'" value="Voltar para a lista">
<br />
Nome: {{ object.title }}
<br />
Autor: {{ object.author }}
<br />
Editora: {{ object.publisher }}
<br />
Gênero: {{ object.genre }}
<br />
Ano: {{ object.year }}
<br />
Descrição: {{ object.description }}

</body>
</html>

templates/biblioteca/livro_form.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Adicionar Livro</title>
</head>
<body>
    <h1>Cadastro de Livros</h1>
    <form method="post" action=".">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Salvar">
        <input type="reset" value="Cancelar" onclick="location.href = '{% url biblioteca:list %}'">
    </form>
</body>
</html>

templates/biblioteca/livro_list.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista de Livros</title>
</head>
<body>
    <h1>Lista de Livros</h1>
    <input type="submit" onclick="location.href = '{% url biblioteca:create %}'" value="Adicionar Livro">
    <ul>
        {% for livro in object_list %}
        <li>{{ livro.title }} - <a href="{% url 'biblioteca:update' pk=livro.id %}">Editar</a>
            <a href="{% url 'biblioteca:detail' pk=livro.id %}">Visualizar</a></li>
            <a href="{% url 'biblioteca:delete' pk=livro.id %}">Apagar</a></li>
        </li>
        {% endfor %}
    </ul>
</body>
</html>